# Generated by Django 2.2.3 on 2019-08-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food', models.CharField(max_length=50)),
            ],
        ),
    ]
