# Generated by Django 2.2.3 on 2019-08-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receip_name', models.CharField(max_length=70)),
                ('ingredients', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ClassName',
        ),
    ]
