# Generated by Django 2.2.3 on 2019-08-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_page', '0002_auto_20190826_1209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReceiptsModel',
            new_name='RecipesModel',
        ),
        migrations.RenameField(
            model_name='recipesmodel',
            old_name='receip_name',
            new_name='recipe_name',
        ),
    ]
