# Generated by Django 2.2.3 on 2019-08-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_page', '0003_auto_20190826_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipesmodel',
            name='recipe_description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
